In [25]:
import pandas as pd

df = pd.read_csv(
    "../../data/out/masj/mmlu_masj_education_levels.tsv",
    sep="\t",
    header=0,
)

In [26]:
df

,src,answer,options,category,question,cot_content,question_id,answer_index,total_tokens,meta_cluster,base_cluster,masj_complexity,masj_rating
0,ori_mmlu-jurisprudence,C,['There is no distinction between the two form...,law,Which of the following criticisms of Llewellyn...,NaN,1286,2,81,Legal Interpretation,Legal Theory Interpretations,graduate,9.0
1,ori_mmlu-international_law,E,"['Article 19', 'Article 11', 'Article 12', 'Ar...",law,Which of the following articles are not qualif...,NaN,1293,4,38,Legal Interpretation,Constitutional Law,undergraduate,9.0
2,ori_mmlu-management,D,"['Work delegation', 'Workload balancing', 'Wor...",business,As what is ensuring that one individual does n...,NaN,83,3,49,Economics & Finance MCQs,Business & Marketing Queries,high_school_and_easier,9.0
3,stemez-Business,J,"['$308.25', '$142.75', '$199.99', '$225.85', '...",business,Margaret Denault recently rented a truck to dr...,NaN,94,9,118,Economics & Finance MCQs,Business Finance Questions,high_school_and_easier,10.0
4,stemez-Business,I,"['$60,000', '$43,200', '$1,794', '$25,000', '$...",business,The tax rate in the town of Centerville is 11(...,NaN,104,8,102,Economics & Finance MCQs,Business Finance Questions,high_school_and_easier,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12027,ori_mmlu-high_school_macroeconomics,F,['Higher interest rates that result from borro...,economics,"The ""crowding-out"" effect refers to which of t...",NaN,7681,5,150,Economics & Finance MCQs,Economic Concepts & Policies,undergraduate,9.0
12028,ori_mmlu-high_school_macroeconomics,A,['Lower reserve requirements; lower the discou...,economics,Which of the following lists contains only Fed...,NaN,7683,0,124,Economics & Finance MCQs,Economic Concepts & Policies,undergraduate,9.0
12029,ori_mmlu-high_school_macroeconomics,I,['The productivity of labor in country X is 75...,economics,Output in country X is 30000 units and there a...,NaN,7684,8,206,Economics & Finance MCQs,Economic Concepts & Policies,high_school_and_easier,9.0
12030,ori_mmlu-high_school_macroeconomics,B,"['an increase in net exports', 'a decrease in ...",economics,A use of easy money (expansionary) policy by t...,NaN,7685,1,58,Economics & Finance MCQs,Economic Concepts & Policies,undergraduate,9.0
12031,ori_mmlu-high_school_macroeconomics,J,['The equilibrium price is indeterminate while...,economics,Suppose the demand for a particular product fa...,NaN,7686,9,156,Economics & Finance MCQs,Economic Concepts & Policies,high_school_and_easier,9.0

In [27]:
len(df)

12032

In [28]:
df.columns

Index(['src', 'answer', 'options', 'category', 'question', 'cot_content',
       'question_id', 'answer_index', 'total_tokens', 'meta_cluster',
       'base_cluster', 'masj_complexity', 'masj_rating'],
      dtype='object')

In [29]:
df = df[df["masj_rating"] >= 9]

In [30]:
df

,src,answer,options,category,question,cot_content,question_id,answer_index,total_tokens,meta_cluster,base_cluster,masj_complexity,masj_rating
0,ori_mmlu-jurisprudence,C,['There is no distinction between the two form...,law,Which of the following criticisms of Llewellyn...,NaN,1286,2,81,Legal Interpretation,Legal Theory Interpretations,graduate,9.0
1,ori_mmlu-international_law,E,"['Article 19', 'Article 11', 'Article 12', 'Ar...",law,Which of the following articles are not qualif...,NaN,1293,4,38,Legal Interpretation,Constitutional Law,undergraduate,9.0
2,ori_mmlu-management,D,"['Work delegation', 'Workload balancing', 'Wor...",business,As what is ensuring that one individual does n...,NaN,83,3,49,Economics & Finance MCQs,Business & Marketing Queries,high_school_and_easier,9.0
3,stemez-Business,J,"['$308.25', '$142.75', '$199.99', '$225.85', '...",business,Margaret Denault recently rented a truck to dr...,NaN,94,9,118,Economics & Finance MCQs,Business Finance Questions,high_school_and_easier,10.0
4,stemez-Business,I,"['$60,000', '$43,200', '$1,794', '$25,000', '$...",business,The tax rate in the town of Centerville is 11(...,NaN,104,8,102,Economics & Finance MCQs,Business Finance Questions,high_school_and_easier,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12027,ori_mmlu-high_school_macroeconomics,F,['Higher interest rates that result from borro...,economics,"The ""crowding-out"" effect refers to which of t...",NaN,7681,5,150,Economics & Finance MCQs,Economic Concepts & Policies,undergraduate,9.0
12028,ori_mmlu-high_school_macroeconomics,A,['Lower reserve requirements; lower the discou...,economics,Which of the following lists contains only Fed...,NaN,7683,0,124,Economics & Finance MCQs,Economic Concepts & Policies,undergraduate,9.0
12029,ori_mmlu-high_school_macroeconomics,I,['The productivity of labor in country X is 75...,economics,Output in country X is 30000 units and there a...,NaN,7684,8,206,Economics & Finance MCQs,Economic Concepts & Policies,high_school_and_easier,9.0
12030,ori_mmlu-high_school_macroeconomics,B,"['an increase in net exports', 'a decrease in ...",economics,A use of easy money (expansionary) policy by t...,NaN,7685,1,58,Economics & Finance MCQs,Economic Concepts & Policies,undergraduate,9.0
12031,ori_mmlu-high_school_macroeconomics,J,['The equilibrium price is indeterminate while...,economics,Suppose the demand for a particular product fa...,NaN,7686,9,156,Economics & Finance MCQs,Economic Concepts & Policies,high_school_and_easier,9.0

In [31]:
df.rename(columns={"masj_complexity": "masj_education_level"}, inplace=True)

/var/folders/62/r46p4vgs7m5bbync7hl0ykjc0000gp/T/ipykernel_11907/2377708883.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"masj_complexity": "masj_education_level"}, inplace=True)

In [32]:
df.drop(columns=["masj_rating"], inplace=True)

/var/folders/62/r46p4vgs7m5bbync7hl0ykjc0000gp/T/ipykernel_11907/3479127213.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["masj_rating"], inplace=True)

In [33]:
df.value_counts("masj_education_level")

masj_education_level
undergraduate             6736
high_school_and_easier    2378
graduate                  2347
postgraduate               106
Name: count, dtype: int64

In [34]:
df.to_csv("../../data/out/masj/mmlu_masj_education_level_filtered.tsv", sep="\t", index=False)